/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.24
 * Generated at: 2019-11-26 13:42:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tag.web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class head_tag
    extends javax.servlet.jsp.tagext.SimpleTagSupport
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.servlet.jsp.JspContext jspContext;
  private java.io.Writer _jspx_sout;
  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public void setJspContext(javax.servlet.jsp.JspContext ctx) {
    super.setJspContext(ctx);
    java.util.ArrayList _jspx_nested = null;
    java.util.ArrayList _jspx_at_begin = null;
    java.util.ArrayList _jspx_at_end = null;
    this.jspContext = new org.apache.jasper.runtime.JspContextWrapper(this, ctx, _jspx_nested, _jspx_at_begin, _jspx_at_end, null);
  }

  public javax.servlet.jsp.JspContext getJspContext() {
    return this.jspContext;
  }

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    return _jsp_instancemanager;
  }

  private void _jspInit(javax.servlet.ServletConfig config) {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(config.getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(config);
  }

  public void _jspDestroy() {
  }

  public void doTag() throws javax.servlet.jsp.JspException, java.io.IOException {
    javax.servlet.jsp.PageContext _jspx_page_context = (javax.servlet.jsp.PageContext)jspContext;
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest) _jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse) _jspx_page_context.getResponse();
    javax.servlet.http.HttpSession session = _jspx_page_context.getSession();
    javax.servlet.ServletContext application = _jspx_page_context.getServletContext();
    javax.servlet.ServletConfig config = _jspx_page_context.getServletConfig();
    javax.servlet.jsp.JspWriter out = jspContext.getOut();
    _jspInit(config);
    jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,jspContext);

    try {
      out.write("<!-- 모든 페이지 공통 헤더 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div style=\"margin-top: 20px;\" align=\"center\">\r\n");
      out.write("\t<a href=\"main.jsp\" target=\"_self\"> <img\r\n");
      out.write("\t\tsrc=\"resources/img/temp.png\" height=\"70px\" alt=\"welcome page\" />\r\n");
      out.write("\t</a><br>\r\n");
      out.write("</div>\r\n");
      out.write("<div>\r\n");
      out.write("\t<form action=\"http://localhost:8080/yunwon_free/BabyServlet?key=logout\"\r\n");
      out.write("\t\tmethod=\"post\">\r\n");
      out.write("\t\t<h4 id=\"content2\">\r\n");
      out.write("\t\t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("님, 환영합니다!&nbsp;&nbsp;\r\n");
      out.write("\t\t\t<button type=\"submit\" class=\"btn btn-outline-light\"\r\n");
      out.write("\t\t\t\tstyle=\"margin-right: 70px;\">Logout</button>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t</h4>\r\n");
      out.write("</div>\r\n");
      out.write("<header>\r\n");
      out.write("\t<div class=\"navbar-nav-scroll\" style=\"margin-right: 60px;\">\r\n");
      out.write("\t\t<ul class=\"nav justify-content-end\">\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link active li_col\"\r\n");
      out.write("\t\t\t\thref=\"main.jsp\">HOME</a></li>\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link li_col\"\r\n");
      out.write("\t\t\t\thref=\"baby_family.jsp\">FAMILY</a></li>\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link li_col\"\r\n");
      out.write("\t\t\t\thref=\"baby_life.jsp\">LIFE</a></li>\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link li_col\"\r\n");
      out.write("\t\t\t\thref=\"http://localhost:8080/yunwon_free/BabyServlet?key=diary\"\r\n");
      out.write("\t\t\t\ttarget=\"_self\">DIARY</a></li>\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link li_col\"\r\n");
      out.write("\t\t\t\thref=\"baby_album.jsp\">ALBUM</a></li>\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link li_col\"\r\n");
      out.write("\t\t\t\thref=\"baby_map.jsp\">MAP</a></li>\r\n");
      out.write("\t\t\t");

					if (session.getAttribute("id").equals("admin")) {
			
      out.write("\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link li_col\"\r\n");
      out.write("\t\t\t\thref=\"http://localhost:8080/yunwon_free/BabyServlet?key=list\"\r\n");
      out.write("\t\t\t\ttarget=\"_self\" style=\"color: #484c7f;\">ADMIN</a></li>\r\n");
      out.write("\t\t\t");

					}
			
      out.write("\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("</header>");
    } catch( java.lang.Throwable t ) {
      if( t instanceof javax.servlet.jsp.SkipPageException )
          throw (javax.servlet.jsp.SkipPageException) t;
      if( t instanceof java.io.IOException )
          throw (java.io.IOException) t;
      if( t instanceof java.lang.IllegalStateException )
          throw (java.lang.IllegalStateException) t;
      if( t instanceof javax.servlet.jsp.JspException )
          throw (javax.servlet.jsp.JspException) t;
      throw new javax.servlet.jsp.JspException(t);
    } finally {
      jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,super.getJspContext());
      ((org.apache.jasper.runtime.JspContextWrapper) jspContext).syncEndTagFile();
    }
  }
}
